// UI copy for the agent pages, in Portuguese and English. Facts in `mastery` come from the
// official 13.06 patch notes (22/09/2026).
export const strings = {
  pt: {
    api: 'pt-BR', skip: 'Pular para o conteúdo', home: 'Início', agents: 'Agentes', maps: 'Mapas', role: 'Função',
    bio: 'Biografia', origin: 'Origem', realName: 'Nome real', element: 'Elemento', scene: 'Cenário', number: 'Agente nº',
    soon: 'Biografia completa em breve. Por enquanto, o resumo oficial.',
    tabs: { label: 'Seções do agente', perfil: 'Perfil', biografia: 'Biografia', habilidades: 'Habilidades', video: 'Em ação', maestria: 'Maestria' },
    noVideo: 'Ainda não há vídeo para este agente.',
    kitTitle: 'Habilidades', kitNav: 'Escolha uma habilidade', passive: 'Passiva',
    slotType: { C: 'Habilidade', Q: 'Habilidade', E: 'Assinatura', X: 'Supremo' },
    video: 'Arquivo // Vídeo',
    prev: 'Agente anterior', next: 'Próximo agente', keys: '← → trocam de agente',
    loading: 'Carregando arquivo…', error: 'Não foi possível carregar os dados do agente.', retry: 'Tentar novamente',
    footer: ['Projeto de fã não oficial', 'VALORANT e Riot Games são marcas de seus respectivos proprietários.'],
    portrait: (name) => `Retrato de ${name}`,
    mastery: {
      kicker: 'Patch 13.06', title: 'Maestria de Agente', locale: 'pt-BR', retry: 'Tentar novamente',
      intro: 'O sistema de maestria chegou no patch 13.06, em 22 de setembro de 2026, e mede o quanto você joga com cada agente.',
      steps: [
        ['Jogue', 'Partidas nos modos compatíveis rendem Pontos de Maestria (PM) para o agente que você usou.'],
        ['Ganhe bônus', 'Vitórias e bom desempenho dão PM extra.'],
        ['Suba de nível', 'Os PM fazem o nível do ato subir, e cada nível do ato também conta para o vitalício.'],
      ],
      actTitle: 'Nível do ato',
      actText: 'Cada agente tem 10 níveis por ato, que zeram quando um ato novo começa. Nos níveis 4, 7 e 10, o retrato do agente ganha uma marca nova.',
      accent: 'Marca no retrato', over: 'Continua até o fim do ato',
      lifeTitle: 'Nível vitalício',
      lifeText: 'O nível vitalício nunca zera: cada nível de ato soma 1 nele. É ele que libera a trilha de recompensas do agente, e os itens são comprados com Kingdom Credits. O progresso de antes do patch não foi aproveitado: todo mundo começou do zero.',
      rewardsTitle: 'Trilha de recompensas',
      rewardsNote: 'A trilha também tem itens novos, que ainda não aparecem na base pública de dados. Estes são os 10 itens que o agente já tinha.',
      rewardsError: 'Não foi possível carregar a trilha de recompensas.',
      types: { Title: 'Título', Spray: 'Spray', PlayerCard: 'Card', EquippableCharmLevel: 'Chaveiro', EquippableSkinLevel: 'Skin' },
      cardAlt: (name) => `Retrato de ${name} no card de maestria`,
      cardCaption: 'Moldura oficial do card de maestria com o retrato do agente. Montagem do fansite.',
      idTitle: 'ID de Agente',
      idText: 'Um cartão do agente que você desbloqueia, personaliza e equipa com peças da trilha de recompensas.',
    },
  },
  en: {
    api: 'en-US', skip: 'Skip to content', home: 'Home', agents: 'Agents', maps: 'Maps', role: 'Role',
    bio: 'Biography', origin: 'Origin', realName: 'Real name', element: 'Element', scene: 'Scene', number: 'Agent no.',
    soon: 'Full biography coming soon. For now, the official summary.',
    tabs: { label: 'Agent sections', perfil: 'Profile', biografia: 'Biography', habilidades: 'Abilities', video: 'In action', maestria: 'Mastery' },
    noVideo: 'No video for this agent yet.',
    kitTitle: 'Abilities', kitNav: 'Pick an ability', passive: 'Passive',
    slotType: { C: 'Ability', Q: 'Ability', E: 'Signature', X: 'Ultimate' },
    video: 'Archive // Video',
    prev: 'Previous agent', next: 'Next agent', keys: '← → switch agents',
    loading: 'Loading file…', error: 'Could not load the agent data.', retry: 'Try again',
    footer: ['Unofficial fan project', 'VALORANT and Riot Games are trademarks of their respective owners.'],
    portrait: (name) => `Portrait of ${name}`,
    mastery: {
      kicker: 'Patch 13.06', title: 'Agent Mastery', locale: 'en-US', retry: 'Try again',
      intro: 'The mastery system arrived in patch 13.06, on September 22, 2026, and tracks how much you play each agent.',
      steps: [
        ['Play', 'Matches in supported modes earn Mastery Points (MP) for the agent you played.'],
        ['Earn bonuses', 'Wins and strong performances grant extra MP.'],
        ['Level up', 'MP raises your act level, and every act level also counts toward your lifetime level.'],
      ],
      actTitle: 'Act level',
      actText: 'Every agent has 10 levels per act, which reset when a new act begins. At levels 4, 7 and 10, the agent portrait gets a new accent.',
      accent: 'Portrait accent', over: 'Keeps going until the act ends',
      lifeTitle: 'Lifetime level',
      lifeText: "The lifetime level never resets: each act level adds 1 to it. It unlocks the agent's reward track, and items are bought with Kingdom Credits. Progress from before the patch did not carry over: everyone started from zero.",
      rewardsTitle: 'Reward track',
      rewardsNote: 'The track also has new items that are not in the public database yet. These are the 10 items the agent already had.',
      rewardsError: 'Could not load the reward track.',
      types: { Title: 'Title', Spray: 'Spray', PlayerCard: 'Card', EquippableCharmLevel: 'Buddy', EquippableSkinLevel: 'Skin' },
      cardAlt: (name) => `${name} on the mastery card`,
      cardCaption: 'Official mastery card frame with the agent portrait. Fansite composite.',
      idTitle: 'Agent ID',
      idText: 'An agent card you unlock, customize and equip with pieces from the reward track.',
    },
  },
};
